name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Rust Toolchain
        uses: actions-rs/install@v0.1
        with:
          crate: wrangler
          version: latest
          use-tool-cache: true
      
      - name: Publish
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: wrangler publish
